Dodana liczba aktywnych rowerow na liscie stacji
io2-2021-wed-brodka/G_User-Tech pull request #12
Opened 2021-05-22 09:16 UTC by KrolikJakub

2021-05-22 18:32 UTC, arkadiusz-gorecki requested changes
Liczba rowerów uwzględnia liczbę zarezerwowanych rowerów. Ten endpoint był wykorzystywany na G_Admin i adminowi powinny się wyświetlać liczba wraz z zarezerwowanymi rowerami ale nie userowi. Chyba należałoby dodać nowy endpoint na backendzie który zwraca aktywne stację z liczbą aktywnych rowerów.

2021-05-23 15:14 UTC, tomkarw commented
> Liczba rowerów uwzględnia liczbę zarezerwowanych rowerów. Ten endpoint był wykorzystywany na G_Admin i adminowi powinny się wyświetlać liczba wraz z zarezerwowanymi rowerami ale nie userowi. Chyba należałoby dodać nowy endpoint na backendzie który zwraca aktywne stację z liczbą aktywnych rowerów.
@arkadiusz-gorecki `GET stations/active` którego tu używamy ma w specyfikacji pole `activeBikesCount`, nie rozumiem w czym problem

2021-05-23 15:21 UTC, arkadiusz-gorecki commented
> > Liczba rowerów uwzględnia liczbę zarezerwowanych rowerów. Ten endpoint był wykorzystywany na G_Admin i adminowi powinny się wyświetlać liczba wraz z zarezerwowanymi rowerami ale nie userowi. Chyba należałoby dodać nowy endpoint na backendzie który zwraca aktywne stację z liczbą aktywnych rowerów.
> > @arkadiusz-gorecki `GET stations/active` którego tu używamy ma w specyfikacji pole `activeBikesCount`, nie rozumiem w czym problem

Nazywa się `activeBikesCount` ale zwraca również zarezerwowane, nazwa jest błędna. Nie wiem z czego to wynika ale jak testowałem to na podglądzie stacji z punktu widzenia Usera liczyło też zarezerwowane rowery.

2021-05-23 15:23 UTC, tomkarw commented
> > > Liczba rowerów uwzględnia liczbę zarezerwowanych rowerów. Ten endpoint był wykorzystywany na G_Admin i adminowi powinny się wyświetlać liczba wraz z zarezerwowanymi rowerami ale nie userowi. Chyba należałoby dodać nowy endpoint na backendzie który zwraca aktywne stację z liczbą aktywnych rowerów.
> > > @arkadiusz-gorecki `GET stations/active` którego tu używamy ma w specyfikacji pole `activeBikesCount`, nie rozumiem w czym problem
> 
> Nazywa się `activeBikesCount` ale zwraca również zarezerwowane, nazwa jest błędna. Nie wiem z czego to wynika ale jak testowałem to na podglądzie stacji z punktu widzenia Usera liczyło też zarezerwowane rowery.

W takim razie do poprawki na backendzie, zrobię to w zbiorczym zadaniu z walidacją ról przy logowaniu i `POST stations`.

2021-05-23 15:49 UTC, tomkarw requested changes
A może być `Bikes Count` za `Station Name`

2021-05-23 15:49 UTC, tomkarw commented on src/Pages/stationList.tsx
> +                <Box p={0} m={1} style={{ marginRight: "30px" }}>
A może to być za `Station Name`?

2021-05-27 18:12 UTC, tomkarw approved these changes

2021-05-27 18:12 UTC, arkadiusz-gorecki approved these changes

2021-05-29 10:07 UTC, merged